### ISSUE TITLE
[ERROR] TypeError: fwrite() expects parameter 1 to be resource, null given(0)

### ISSUE THREAD

**Issue by askasky** [hyperf/nats#1]
安装好了nats，使用默认配置，并生成了个名叫BoardConsumer的消费者：
```
/**
 * @Consumer(subject="mo.operation.finish", name ="BoardConsumer", nums=1)
 */
class BoardConsumer extends AbstractConsumer
{
    public function consume(Message $payload)
    {
        var_dump($payload->getBody());
    }
}
```
启动服务后控制台每10秒出现下面的提示：
```php
'default' => [
        'driver' => Hyperf\Nats\Driver\NatsDriver::class,
        'encoder' => Hyperf\Nats\Encoders\JSONEncoder::class,
        'timeout' => 10.0,  // 把timeout改为-1后就不会提示了
        'options' => [

[ERROR] TypeError: fwrite() expects parameter 1 to be resource, null given(0) in /Users/shenyongxian/project/newasia/na-erp-back/vendor/hyperf/nats/src/Connection.php:510
Stack trace:
#0 /Users/shenyongxian/project/newasia/na-erp-back/vendor/hyperf/nats/src/Connection.php(510): fwrite(NULL, 'SUB mo.operatio...')
#1 /Users/shenyongxian/project/newasia/na-erp-back/vendor/hyperf/nats/src/Connection.php(324): Hyperf\Nats\Connection->send('SUB mo.operatio...')
#2 /Users/shenyongxian/project/newasia/na-erp-back/vendor/hyperf/nats/src/EncodedConnection.php(67): Hyperf\Nats\Connection->subscribe('mo.operation.fi...', Object(Closure))
#3 /Users/shenyongxian/project/newasia/na-erp-back/vendor/hyperf/nats/src/Driver/NatsDriver.php(106): Hyperf\Nats\EncodedConnection->subscribe('mo.operation.fi...', Object(Closure))
#4 /Users/shenyongxian/project/newasia/na-erp-back/vendor/hyperf/nats/src/ConsumerManager.php(109): Hyperf\Nats\Driver\NatsDriver->subscribe('mo.operation.fi...', '', Object(Closure))
#5 /Users/shenyongxian/project/newasia/na-erp-back/vendor/hyperf/process/src/AbstractProcess.php(134): class@anonymous->handle()
#6 {main}
[INFO] Process[BoardConsumer-mo.operation.finish.0] stoped.
```

**Comment by dracovish** [comment]
![image](https://user-images.githubusercontent.com/26037952/115649943-de7c3c00-a35a-11eb-8847-d9b841a68d4a.png)

复现不了

**Comment by dracovish** [comment]
```
<?php

declare(strict_types=1);
/**
 * This file is part of Hyperf.
 *
 * @link     https://www.hyperf.io
 * @document https://hyperf.wiki
 * @contact  group@hyperf.io
 * @license  https://github.com/hyperf/hyperf/blob/master/LICENSE
 */
namespace App\Nats\Consumer;

use Hyperf\Nats\AbstractConsumer;
use Hyperf\Nats\Annotation\Consumer;
use Hyperf\Nats\Message;

/**
 * @Consumer(subject="mo.operation.finish", queue="mo.operation.finish", name="BoardConsumer", nums=1)
 */
class BoardConsumer extends AbstractConsumer
{
    public function consume(Message $payload)
    {
        var_dump($payload->getBody());
    }
}

```
